# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.1-1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: autopep8-wrapper
    -   id: check-ast
    -   id: flake8
        args: [--max-line-length=120]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: trailing-whitespace
-   repo: https://github.com/FalconSocial/pre-commit-python-sorter
    rev: HEAD
    hooks:
    -   id: python-import-sorter
