language: python
cache: pip
python:
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
- pypy3.5
sudo: false
install:
- pip install .[test] codecov
matrix:
  fast_finish: true
  allow_failures:
  - python: pypy3.5
script:
- nosetests --cover-erase --cover-package=pyDownload  --cover-branches --with-coverage
- codecov
