language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
  - "pypy2.7"
  - "pypy3.5"
sudo: false
install:
  - pip install .[test] codecov
script:
  - nosetests --cover-erase --cover-package=pyDownload  --cover-branches --with-coverage
  - codecov
